-- USERS (50)
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso1','usuario1@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso2','usuario2@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso3','usuario3@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso4','usuario4@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso5','usuario5@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso6','usuario6@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso7','usuario7@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso8','usuario8@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso9','usuario9@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso10','usuario10@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso11','usuario11@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso12','usuario12@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso13','usuario13@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso14','usuario14@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso15','usuario15@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso16','usuario16@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso17','usuario17@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso18','usuario18@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso19','usuario19@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso20','usuario20@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso21','usuario21@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso22','usuario22@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso23','usuario23@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso24','usuario24@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso25','usuario25@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso26','usuario26@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso27','usuario27@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso28','usuario28@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso29','usuario29@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso30','usuario30@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso31','usuario31@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso32','usuario32@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso33','usuario33@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso34','usuario34@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso35','usuario35@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso36','usuario36@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso37','usuario37@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso38','usuario38@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso39','usuario39@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso40','usuario40@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso41','usuario41@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso42','usuario42@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso43','usuario43@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso44','usuario44@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso45','usuario45@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso46','usuario46@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso47','usuario47@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso48','usuario48@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso49','usuario49@correo-falso.test');
INSERT INTO USERS (name_users,email) VALUES ('UsuarioFalso50','usuario50@correo-falso.test');

-- TASKSAGENDA (50)
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (1,'Tarea Inventada 1','Descripción ficticia de tarea 1','2026-01-02','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (2,'Tarea Inventada 2','Descripción ficticia de tarea 2','2026-01-03','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (3,'Tarea Inventada 3','Descripción ficticia de tarea 3','2026-01-04','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (4,'Tarea Inventada 4','Descripción ficticia de tarea 4','2026-01-05','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (5,'Tarea Inventada 5','Descripción ficticia de tarea 5','2026-01-06','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (6,'Tarea Inventada 6','Descripción ficticia de tarea 6','2026-01-07','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (7,'Tarea Inventada 7','Descripción ficticia de tarea 7','2026-01-08','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (8,'Tarea Inventada 8','Descripción ficticia de tarea 8','2026-01-09','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (9,'Tarea Inventada 9','Descripción ficticia de tarea 9','2026-01-10','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (10,'Tarea Inventada 10','Descripción ficticia de tarea 10','2026-01-11','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (11,'Tarea Inventada 11','Descripción ficticia de tarea 11','2026-01-12','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (12,'Tarea Inventada 12','Descripción ficticia de tarea 12','2026-01-13','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (13,'Tarea Inventada 13','Descripción ficticia de tarea 13','2026-01-14','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (14,'Tarea Inventada 14','Descripción ficticia de tarea 14','2026-01-15','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (15,'Tarea Inventada 15','Descripción ficticia de tarea 15','2026-01-16','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (16,'Tarea Inventada 16','Descripción ficticia de tarea 16','2026-01-17','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (17,'Tarea Inventada 17','Descripción ficticia de tarea 17','2026-01-18','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (18,'Tarea Inventada 18','Descripción ficticia de tarea 18','2026-01-19','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (19,'Tarea Inventada 19','Descripción ficticia de tarea 19','2026-01-20','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (20,'Tarea Inventada 20','Descripción ficticia de tarea 20','2026-01-21','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (21,'Tarea Inventada 21','Descripción ficticia de tarea 21','2026-01-22','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (22,'Tarea Inventada 22','Descripción ficticia de tarea 22','2026-01-23','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (23,'Tarea Inventada 23','Descripción ficticia de tarea 23','2026-01-24','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (24,'Tarea Inventada 24','Descripción ficticia de tarea 24','2026-01-25','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (25,'Tarea Inventada 25','Descripción ficticia de tarea 25','2026-01-26','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (26,'Tarea Inventada 26','Descripción ficticia de tarea 26','2026-01-27','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (27,'Tarea Inventada 27','Descripción ficticia de tarea 27','2026-01-28','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (28,'Tarea Inventada 28','Descripción ficticia de tarea 28','2026-01-29','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (29,'Tarea Inventada 29','Descripción ficticia de tarea 29','2026-01-30','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (30,'Tarea Inventada 30','Descripción ficticia de tarea 30','2026-01-31','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (31,'Tarea Inventada 31','Descripción ficticia de tarea 31','2026-02-01','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (32,'Tarea Inventada 32','Descripción ficticia de tarea 32','2026-02-02','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (33,'Tarea Inventada 33','Descripción ficticia de tarea 33','2026-02-03','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (34,'Tarea Inventada 34','Descripción ficticia de tarea 34','2026-02-04','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (35,'Tarea Inventada 35','Descripción ficticia de tarea 35','2026-02-05','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (36,'Tarea Inventada 36','Descripción ficticia de tarea 36','2026-02-06','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (37,'Tarea Inventada 37','Descripción ficticia de tarea 37','2026-02-07','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (38,'Tarea Inventada 38','Descripción ficticia de tarea 38','2026-02-08','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (39,'Tarea Inventada 39','Descripción ficticia de tarea 39','2026-02-09','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (40,'Tarea Inventada 40','Descripción ficticia de tarea 40','2026-02-10','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (41,'Tarea Inventada 41','Descripción ficticia de tarea 41','2026-02-11','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (42,'Tarea Inventada 42','Descripción ficticia de tarea 42','2026-02-12','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (43,'Tarea Inventada 43','Descripción ficticia de tarea 43','2026-02-13','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (44,'Tarea Inventada 44','Descripción ficticia de tarea 44','2026-02-14','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (45,'Tarea Inventada 45','Descripción ficticia de tarea 45','2026-02-15','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (46,'Tarea Inventada 46','Descripción ficticia de tarea 46','2026-02-16','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (47,'Tarea Inventada 47','Descripción ficticia de tarea 47','2026-02-17','PROGRESO','ALTA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (48,'Tarea Inventada 48','Descripción ficticia de tarea 48','2026-02-18','PENDIENTE','BAJA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (49,'Tarea Inventada 49','Descripción ficticia de tarea 49','2026-02-19','HECHA','MEDIA');
INSERT INTO TASKSAGENDA (owner_user_id,title,description_agenda,due_date,status_agenda,priority_agenda) VALUES (50,'Tarea Inventada 50','Descripción ficticia de tarea 50','2026-02-20','PROGRESO','ALTA');

-- TASK_SHARES (50)
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (1,6,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (2,7,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (3,8,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (4,9,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (5,10,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (6,11,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (7,12,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (8,13,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (9,14,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (10,15,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (11,16,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (12,17,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (13,18,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (14,19,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (15,20,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (16,21,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (17,22,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (18,23,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (19,24,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (20,25,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (21,26,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (22,27,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (23,28,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (24,29,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (25,30,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (26,31,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (27,32,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (28,33,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (29,34,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (30,35,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (31,36,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (32,37,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (33,38,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (34,39,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (35,40,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (36,41,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (37,42,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (38,43,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (39,44,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (40,45,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (41,46,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (42,47,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (43,48,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (44,49,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (45,50,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (46,1,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (47,2,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (48,3,'WRITE');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (49,4,'READ');
INSERT INTO TASK_SHARES (task_id,shared_with_user_id,permission) VALUES (50,5,'WRITE');

-- EVENTS (50)
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (1,'Evento Ficticio 1','Descripción ficticia del evento 1','2026-02-02 09:00:00','2026-02-02 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (2,'Evento Ficticio 2','Descripción ficticia del evento 2','2026-02-03 09:00:00','2026-02-03 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (3,'Evento Ficticio 3','Descripción ficticia del evento 3','2026-02-04 09:00:00','2026-02-04 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (4,'Evento Ficticio 4','Descripción ficticia del evento 4','2026-02-05 09:00:00','2026-02-05 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (5,'Evento Ficticio 5','Descripción ficticia del evento 5','2026-02-06 09:00:00','2026-02-06 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (6,'Evento Ficticio 6','Descripción ficticia del evento 6','2026-02-07 09:00:00','2026-02-07 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (7,'Evento Ficticio 7','Descripción ficticia del evento 7','2026-02-08 09:00:00','2026-02-08 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (8,'Evento Ficticio 8','Descripción ficticia del evento 8','2026-02-09 09:00:00','2026-02-09 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (9,'Evento Ficticio 9','Descripción ficticia del evento 9','2026-02-10 09:00:00','2026-02-10 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (10,'Evento Ficticio 10','Descripción ficticia del evento 10','2026-02-11 09:00:00','2026-02-11 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (11,'Evento Ficticio 11','Descripción ficticia del evento 11','2026-02-12 09:00:00','2026-02-12 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (12,'Evento Ficticio 12','Descripción ficticia del evento 12','2026-02-13 09:00:00','2026-02-13 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (13,'Evento Ficticio 13','Descripción ficticia del evento 13','2026-02-14 09:00:00','2026-02-14 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (14,'Evento Ficticio 14','Descripción ficticia del evento 14','2026-02-15 09:00:00','2026-02-15 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (15,'Evento Ficticio 15','Descripción ficticia del evento 15','2026-02-16 09:00:00','2026-02-16 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (16,'Evento Ficticio 16','Descripción ficticia del evento 16','2026-02-17 09:00:00','2026-02-17 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (17,'Evento Ficticio 17','Descripción ficticia del evento 17','2026-02-18 09:00:00','2026-02-18 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (18,'Evento Ficticio 18','Descripción ficticia del evento 18','2026-02-19 09:00:00','2026-02-19 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (19,'Evento Ficticio 19','Descripción ficticia del evento 19','2026-02-20 09:00:00','2026-02-20 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (20,'Evento Ficticio 20','Descripción ficticia del evento 20','2026-02-21 09:00:00','2026-02-21 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (21,'Evento Ficticio 21','Descripción ficticia del evento 21','2026-02-22 09:00:00','2026-02-22 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (22,'Evento Ficticio 22','Descripción ficticia del evento 22','2026-02-23 09:00:00','2026-02-23 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (23,'Evento Ficticio 23','Descripción ficticia del evento 23','2026-02-24 09:00:00','2026-02-24 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (24,'Evento Ficticio 24','Descripción ficticia del evento 24','2026-02-25 09:00:00','2026-02-25 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (25,'Evento Ficticio 25','Descripción ficticia del evento 25','2026-02-26 09:00:00','2026-02-26 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (26,'Evento Ficticio 26','Descripción ficticia del evento 26','2026-02-27 09:00:00','2026-02-27 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (27,'Evento Ficticio 27','Descripción ficticia del evento 27','2026-02-28 09:00:00','2026-02-28 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (28,'Evento Ficticio 28','Descripción ficticia del evento 28','2026-03-01 09:00:00','2026-03-01 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (29,'Evento Ficticio 29','Descripción ficticia del evento 29','2026-03-02 09:00:00','2026-03-02 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (30,'Evento Ficticio 30','Descripción ficticia del evento 30','2026-03-03 09:00:00','2026-03-03 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (31,'Evento Ficticio 31','Descripción ficticia del evento 31','2026-03-04 09:00:00','2026-03-04 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (32,'Evento Ficticio 32','Descripción ficticia del evento 32','2026-03-05 09:00:00','2026-03-05 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (33,'Evento Ficticio 33','Descripción ficticia del evento 33','2026-03-06 09:00:00','2026-03-06 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (34,'Evento Ficticio 34','Descripción ficticia del evento 34','2026-03-07 09:00:00','2026-03-07 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (35,'Evento Ficticio 35','Descripción ficticia del evento 35','2026-03-08 09:00:00','2026-03-08 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (36,'Evento Ficticio 36','Descripción ficticia del evento 36','2026-03-09 09:00:00','2026-03-09 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (37,'Evento Ficticio 37','Descripción ficticia del evento 37','2026-03-10 09:00:00','2026-03-10 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (38,'Evento Ficticio 38','Descripción ficticia del evento 38','2026-03-11 09:00:00','2026-03-11 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (39,'Evento Ficticio 39','Descripción ficticia del evento 39','2026-03-12 09:00:00','2026-03-12 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (40,'Evento Ficticio 40','Descripción ficticia del evento 40','2026-03-13 09:00:00','2026-03-13 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (41,'Evento Ficticio 41','Descripción ficticia del evento 41','2026-03-14 09:00:00','2026-03-14 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (42,'Evento Ficticio 42','Descripción ficticia del evento 42','2026-03-15 09:00:00','2026-03-15 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (43,'Evento Ficticio 43','Descripción ficticia del evento 43','2026-03-16 09:00:00','2026-03-16 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (44,'Evento Ficticio 44','Descripción ficticia del evento 44','2026-03-17 09:00:00','2026-03-17 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (45,'Evento Ficticio 45','Descripción ficticia del evento 45','2026-03-18 09:00:00','2026-03-18 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (46,'Evento Ficticio 46','Descripción ficticia del evento 46','2026-03-19 09:00:00','2026-03-19 10:00:00','TRABAJO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (47,'Evento Ficticio 47','Descripción ficticia del evento 47','2026-03-20 09:00:00','2026-03-20 10:00:00','OTRO');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (48,'Evento Ficticio 48','Descripción ficticia del evento 48','2026-03-21 09:00:00','2026-03-21 10:00:00','REUNION');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (49,'Evento Ficticio 49','Descripción ficticia del evento 49','2026-03-22 09:00:00','2026-03-22 10:00:00','PERSONAL');
INSERT INTO EVENTS (owner_user_id,title,description_event,start_at,end_at,event_type) VALUES (50,'Evento Ficticio 50','Descripción ficticia del evento 50','2026-03-23 09:00:00','2026-03-23 10:00:00','TRABAJO');

-- EVENT_SHARES (50)
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (1,11,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (2,12,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (3,13,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (4,14,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (5,15,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (6,16,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (7,17,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (8,18,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (9,19,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (10,20,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (11,21,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (12,22,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (13,23,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (14,24,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (15,25,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (16,26,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (17,27,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (18,28,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (19,29,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (20,30,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (21,31,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (22,32,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (23,33,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (24,34,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (25,35,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (26,36,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (27,37,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (28,38,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (29,39,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (30,40,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (31,41,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (32,42,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (33,43,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (34,44,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (35,45,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (36,46,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (37,47,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (38,48,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (39,49,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (40,50,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (41,1,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (42,2,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (43,3,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (44,4,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (45,5,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (46,6,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (47,7,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (48,8,'WRITE');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (49,9,'READ');
INSERT INTO EVENT_SHARES (event_id,shared_with_user_id,permission) VALUES (50,10,'WRITE');